### ISSUE TITLE
Any chance of numbered versions in docker hub?

### ISSUE THREAD

**Issue by rendhalver** [dweomer/dockerfiles-nginx-auth-ldap#1]

**Comment by dweomer** [comment]
Well, I *can* pull the current `latest` and push it up with the tag `1.13.5-on-alpine-3.5`. Will that suffice?

**Comment by rendhalver** [comment]
Sounds awesome to me. :) Thanks.
Could you built that into your release process?

**Comment by dweomer** [comment]
I don't work at keeping up with the `nginx` or `alpine` sources/images but I can easily tag this in git when I do make changes and tweak the Docker Hub automated build accordingly. I have done this for the `v1.13.5-on-alpine-3.5` tag and it is currently building.

**Comment by dweomer** [comment]
Pushed: https://hub.docker.com/r/dweomer/nginx-auth-ldap/tags/
